<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>The &quot;Learn Spring Security Core&quot; Course: A Full Registration Flow</description>
    <name>learn-spring-security-parent</name>

    <groupId>com.baeldung.m2</groupId>
    <artifactId>learn-spring-security-m2</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>m2-lesson1</module>
        <module>a-simple-registration-flow-start</module>
        <module>a-simple-registration-flow-end</module>
        <module>m2-lesson2</module>
        <module>authentication-using-real-users-start</module>
        <module>authentication-using-real-users-end</module>
        <module>m2-lesson3</module>
        <module>activate-new-account-via-email-start</module>
        <module>activate-new-account-via-email-end</module>
        <module>m2-lesson4</module>
        <module>forgot-password-start</module>
        <module>forgot-password-end</module>
        <module>m2-lesson5</module>
        <module>security-questions-start</module>
        <module>security-questions-end</module>
        <module>m2-lesson6</module>
        <module>m2-lesson7</module>
        <module>password-strength-start</module>
        <module>password-strength-end</module>
    </modules>

</project>
