-- HSQL Schema
drop table if exists security_question;
drop table if exists security_question_definition;
drop table if exists users_roles;
drop table if exists role;
drop table if exists verification_token;
drop table if exists password_reset_token;
drop table if exists persistent_logins;
drop table if exists user;

create table if not exists security_question_definition (
  id bigint generated by default as identity(start with 1) not null  primary key,
  text varchar(255) default null
);

create table if not exists  security_question(
  id bigint generated by default as identity(start with 1) not null  primary key,
  answer varchar(255) default null,
  security_question_definition_id bigint not null,
  user_id bigint not null
);

create table if not exists users_roles (
  user_id bigint not null,
  role_id bigint not null
);

create table if not exists user (
  id bigint generated by default as identity(start with 1) not null  primary key,
  created timestamp default null,
  email varchar(255) default null,
  enabled boolean default false not null,
  password varchar(255) default null,
  secret varchar(255) default null
);

create table if not exists role (
  id bigint generated by default as identity(start with 1) not null  primary key,
  name varchar(255) default null,
);

create table if not exists verification_token (
  id bigint generated by default as identity(start with 1) not null  primary key,
  expiry_date timestamp default null,
  token varchar(255) default null,
  user_id bigint not null
);

create table if not exists password_reset_token (
  id bigint generated by default as identity(start with 1) not null  primary key,
  expiry_date datetime default null,
  token varchar(255) default null,
  user_id bigint NOT NULL
);

create table if not exists persistent_logins (
  username varchar_ignorecase(100) not null,
  series varchar(64) primary key,
  token varchar(64) not null,
  last_used timestamp not null
);

